#!/bin/bash
# description:  Start Stop Restart and Status for Tomcat 7
# processname: tomcat7


die () {
    echo >&2 "$@"
    exit 1
}

[ "$#" -eq 1 ] || die "Required argument {start | stop | status | restart}, $# provided"

#JAVA_HOME=/usr/java/jre1.7.0_21
JAVA_HOME=/usr/lib/jvm/java-1.6.0/
export JAVA_HOME
PATH=$JAVA_HOME/bin:$PATH
export PATH
CATALINA_HOME=/usr/share/tomcat7

function status_tomcat() {
	echo "checking tomcat7 status ..."
	wget -o wgetresponse http://localhost:8080
	grep 'response\|failed' wgetresponse
	sudo rm -rf wgetresponse index.html*
}

function start_tomcat () {
	echo "starting tomcat7 ..."
	sh $CATALINA_HOME/bin/startup.sh
}

function stop_tomcat () {
	echo "stopping tomcat7 ..."
	sh $CATALINA_HOME/bin/shutdown.sh
}

case $1 in
start)
	start_tomcat
;; 
stop)   
	stop_tomcat
;; 
status)
	status_tomcat
;;
restart)
	stop_tomcat
	start_tomcat
;; 
esac    
exit 0
